// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1T6s4jb6v5a6iUWIVXsbVqQQurFp4ruc',
    appId: '1:909919373592:web:805eaebaf6482bfed0366d',
    messagingSenderId: '909919373592',
    projectId: 'vsiah-672ab',
    authDomain: 'vsiah-672ab.firebaseapp.com',
    storageBucket: 'vsiah-672ab.appspot.com',
    measurementId: 'G-J9Z5B6VNDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzbUVxjtAEuwYh0z3eQBdxshmsJFZzeDw',
    appId: '1:909919373592:android:ad15d36264747f7ad0366d',
    messagingSenderId: '909919373592',
    projectId: 'vsiah-672ab',
    storageBucket: 'vsiah-672ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaZ5a5mHSSe2fpcsD0XMJwiIOxHDIhk4o',
    appId: '1:909919373592:ios:17e7bbdc60b22d7fd0366d',
    messagingSenderId: '909919373592',
    projectId: 'vsiah-672ab',
    storageBucket: 'vsiah-672ab.appspot.com',
    iosBundleId: 'com.example.vsiah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaZ5a5mHSSe2fpcsD0XMJwiIOxHDIhk4o',
    appId: '1:909919373592:ios:f9e7c058e893f737d0366d',
    messagingSenderId: '909919373592',
    projectId: 'vsiah-672ab',
    storageBucket: 'vsiah-672ab.appspot.com',
    iosBundleId: 'com.example.vsiah.RunnerTests',
  );
}
